In [8]:
import numpy as np
arr1=np.arange(0,10,1)
print("the range from 0 to 10",arr1)

the range from 0 to 10 [0 1 2 3 4 5 6 7 8 9]


In [7]:
import numpy as np
arr1=np.arange(0,10,2)
print("the range from 0 to 10",arr1)

the range from 0 to 10 [0 2 4 6 8]


In [5]:
arr2 = np.linspace(0,2,5)
print("Array using linspace:", arr2)


Array using linspace: [0.  0.5 1.  1.5 2. ]


In [3]:
import numpy as np
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)

print("Flattened version:", arr3.flatten())



Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [4]:
data = np.array([[6, 7, 8], [2, 4, 5]])

print("Original Data:\n", data)

Original Data:
 [[6 7 8]
 [2 4 5]]


In [13]:
import numpy as np
data=np.array([[6,7,8],[2,4,5]])
print("Sum of all elements:", np.sum(data))
print("Column_wise sum:", np.sum(data, axis=0))
print("Row_wise mean:", np.mean(data, axis=1))
print("Maximum value:", np.max(data))


Sum of all elements: 32
Column_wise sum: [ 8 11 13]
Row_wise mean: [7.         3.66666667]
Maximum value: 8


In [16]:
print("Index of max value (flat):", np.argmax(data))
print("Min value:", np.min(data))
print("Standard Deviation:", np.std(data))


Index of max value (flat): 2
Min value: 2
Standard Deviation: 1.9720265943665387


In [17]:
a = np.array([1,2,3,4,5])
print("Original_Array:", a)

Original_Array: [1 2 3 4 5]


In [18]:
array = np.sort(a)
print("Sorted Array:", array)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])

Sorted Array: [1 2 3 4 5]
Indices where value > 4: (array([4]),)
Values > 4: [5]


In [23]:
import numpy as np
a=np.array([[1,3],[7,9]])
b=np.array([1,2,3,4])
print("Matrix:",a)
print("vector:",b)

Matrix: [[1 3]
 [7 9]]
vector: [1 2 3 4]


In [30]:
import numpy as np
a=np.array([[1,3],[7,9]])
b=np.array([1,2])
print("Matrix:",a)
print("vector:",b)
c = a+b
print("addition:",c)

Matrix: [[1 3]
 [7 9]]
vector: [1 2]
addition: [[ 2  5]
 [ 8 11]]


In [38]:
nums = np.array([1,12,13,14,15])
Num= nums > 3
print("filter (nums > 3):", Num)


filter (nums > 3): [False  True  True  True  True]


In [39]:
filtered = nums[Num]
print("Filtered values:", filtered)

result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)

Filtered values: [12 13 14 15]
Even or Odd: ['Odd' 'Even' 'Odd' 'Even' 'Odd']


In [41]:
arr_orig = np.array([1, 2, 30])
arr_view = arr_orig[:]
arr_view[1] = 69
print("Original After View Change:", arr_orig)


Original After View Change: [ 1 69 30]


In [43]:
arr_copy = arr_orig.copy()
arr_copy[2] = 55
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)


Original After Copy Change: [ 1 69 30]
Copy: [ 1 69 55]


In [44]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)
v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)

Horizontal Stack:
 [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [46]:
z = np.arange(9)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)


Split into 3 parts: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [47]:
rand_ints = np.random.randint(0, 100, size=(3, 3))
print("Random Integers:\n", rand_ints)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)


Random Integers:
 [[47 92 28]
 [ 7 19 68]
 [39  6  9]]
Random Normal Distribution:
 [[-0.39362554  0.78776132  0.25742773  0.84553266]
 [-1.45655262 -0.72692067 -0.37500353  1.46827552]]


In [49]:
choices = np.random.choice([1, 3, 6,7], size=5)
print("Random Choices:", choices)
np.random.seed(42)
print("Seeded Random Number:", np.random.rand())

Random Choices: [1 6 6 7 1]
Seeded Random Number: 0.3745401188473625


In [51]:
arr = np.array([10, 20, 30, 40, 70, 60])
print("Original 1D Array:", arr)
print("Element at index 0:", arr[0])
print("Element at last index:", arr[-1])
print("Slice from index 1 to 4:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

Original 1D Array: [10 20 30 40 70 60]
Element at index 0: 10
Element at last index: 60
Slice from index 1 to 4: [20 30 40]
Every second element: [10 30 70]
Reversed array: [60 70 40 30 20 10]


In [52]:
matrix = np.array([[11, 12, 13],
                   [14, 15, 16],
                   [17, 18, 19]])

print("Original Matrix:\n", matrix)
print("Element at (1,2):", matrix[1, 2])
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])
print("Top-left 2x2 block:\n", matrix[:2, :2])


Original Matrix:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Element at (1,2): 16
First row: [11 12 13]
Second column: [12 15 18]
Top-left 2x2 block:
 [[11 12]
 [14 15]]


In [53]:
arr = np.array([5, 10, 15, 20, 25, 30])
mask = arr > 15
print("Boolean Mask:", mask)
print("Values greater than 15:", arr[mask])
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])


Boolean Mask: [False False False  True  True  True]
Values greater than 15: [20 25 30]
Even numbers > 10: [20 30]
