In [1]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt

np.set_printoptions(precision=3, suppress=True)
np.random.seed(42)
print('Setup complete. NumPy', np.__version__)



Setup complete. NumPy 2.0.2


In [9]:
scalar = np.array(5)
vector = np.array([2, 5, 1])
matrix = np.array([[1, 2], [3, 4]])
tensor = np.ones((4, 3, 3))
print("scalar:",scalar)
print("vector:",vector)
print("matrix:",matrix)
print("tensor:",tensor)

scalar: 5
vector: [2 5 1]
matrix: [[1 2]
 [3 4]]
tensor: [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [10]:
for name, arr in [('scalar', scalar), ('vector', vector),
                  ('matrix', matrix), ('tensor', tensor)]:
    print(f'{name:7s} ndim={arr.ndim}  shape={arr.shape}')

scalar  ndim=0  shape=()
vector  ndim=1  shape=(3,)
matrix  ndim=2  shape=(2, 2)
tensor  ndim=3  shape=(4, 3, 3)


In [14]:
A = np.arange(1,7).reshape(2, 3)
B = np.ones((2, 3), dtype=int)

print('A:\n', A)
print('A + B (element-wise add):\n', A + B)
print('A.T  (transpose -> shape', A.T.shape, '):\n', A.T)
print('A.reshape(3, 2):\n', A.reshape(3, 2))
print('A.flatten():', A.flatten())

A:
 [[1 2 3]
 [4 5 6]]
A + B (element-wise add):
 [[2 3 4]
 [5 6 7]]
A.T  (transpose -> shape (3, 2) ):
 [[1 4]
 [2 5]
 [3 6]]
A.reshape(3, 2):
 [[1 2]
 [3 4]
 [5 6]]
A.flatten(): [1 2 3 4 5 6]


In [17]:
T = np.arange(1,10).reshape(3, 3)
print('T:\n', T)

T:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 0, 1])
print('a . b  (dot)   :', np.dot(a, b))
print('a x b  (cross) :', np.cross(a, b))


a . b  (dot)   : 7
a x b  (cross) : [ 2 11 -8]


In [24]:
print('L2 norm          :', la.norm(a))
print('L1 norm          :', la.norm(a, 3))
print('Linf norm        :', la.norm(a, np.inf))
def cosine(u, v):
    return np.dot(u, v) / (la.norm(u) * la.norm(v))

print('cosine(a, b)     :', round(cosine(a, b), 3))

L2 norm          : 3.7416573867739413
L1 norm          : 3.3019272488946263
Linf norm        : 3.0
cosine(a, b)     : 0.454


In [30]:
pairs = [
    (np.array([1, 0, 1]), np.array([1, 0, 1])),
    (np.array([1, 2, 3]), np.array([3, 2, 1])),
    (np.array([2, 0, 0]), np.array([0, 5, 0])),
]

cosine_similarities = []
max_similarity = -1
most_similar_pair_idx = -1

for i, (u, v) in enumerate(pairs, start=1):
    print(f"\nPair {i}:")
    l1_norm_u = la.norm(u, 1)
    l2_norm_u = la.norm(u)
    print(f"  L1 norm of u: {l1_norm_u:.3f}")
    print(f"  L2 norm of u: {l2_norm_u:.3f}")
    cos_sim = cosine(u, v)
    print(f"  Cosine similarity of u and v: {cos_sim:.3f}")
    cosine_similarities.append(cos_sim)
    if cos_sim > max_similarity:
        max_similarity = cos_sim
        most_similar_pair_idx = i
print(f"\nMost similar pair is Pair {most_similar_pair_idx} with a cosine similarity of {max_similarity:.3f}")


Pair 1:
  L1 norm of u: 2.000
  L2 norm of u: 1.414
  Cosine similarity of u and v: 1.000

Pair 2:
  L1 norm of u: 6.000
  L2 norm of u: 3.742
  Cosine similarity of u and v: 0.714

Pair 3:
  L1 norm of u: 2.000
  L2 norm of u: 2.000
  Cosine similarity of u and v: 0.000

Most similar pair is Pair 1 with a cosine similarity of 1.000


In [31]:
A = np.array([[2., 1.],
              [1., 3.]])
B = np.array([[1., 0.],
              [4., 2.]])

print('A @ B (matrix multiply):\n', A @ B)
print('A.T   (transpose):\n', A.T)
print('inverse(A):\n', la.inv(A))
print('trace(A) = sum of diagonal:', np.trace(A))

A @ B (matrix multiply):
 [[ 6.  2.]
 [13.  6.]]
A.T   (transpose):
 [[2. 1.]
 [1. 3.]]
inverse(A):
 [[ 0.6 -0.2]
 [-0.2  0.4]]
trace(A) = sum of diagonal: 5.0


In [32]:
I = np.eye(2)
print('Identity I:\n', I)
print('A @ inv(A) == I ?', np.allclose(A @ la.inv(A), I))


print('A symmetric?', np.allclose(A, A.T))

theta = np.radians(30)
Q = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])
print('Q orthogonal?', np.allclose(Q.T @ Q, I))

Identity I:
 [[1. 0.]
 [0. 1.]]
A @ inv(A) == I ? True
A symmetric? True
Q orthogonal? True


In [34]:
M = np.array([[4., 2.],
              [2., 3.]])
P = np.array([[0., -1.],
              [1.,  0.]])   # a 90-degree rotation

# 1. inverse and trace of M
# YOUR CODE HERE
print("inverse(M):\n", la.inv(M))
print("trace(M) = sum of diagonal:", np.trace(M))
#
# 2. M @ inv(M) == I ?
print("M @ inv(M) == I ?", np.allclose(M @ la.inv(M), I))
# YOUR CODE HERE

# 3. Is M symmetric? Is P orthogonal?
print("M symmetric?", np.allclose(M, M.T))
print("P orthogonal?", np.allclose(P.T @ P, I))

# YOUR CODE HERE


inverse(M):
 [[ 0.375 -0.25 ]
 [-0.25   0.5  ]]
trace(M) = sum of diagonal: 7.0
M @ inv(M) == I ? True
M symmetric? True
P orthogonal? True


In [35]:

A = np.array([[2., 0.],
              [0., 3.]])

vals, vecs = la.eig(A)
print('Eigenvalues  (lambda):', vals)
print('Eigenvectors (columns):\n', vecs)


Eigenvalues  (lambda): [2. 3.]
Eigenvectors (columns):
 [[1. 0.]
 [0. 1.]]


In [36]:
for i in range(len(vals)):
    v = vecs[:, i]
    lhs = A @ v
    rhs = vals[i] * v
    print(f'lambda={vals[i]:.1f}  A v == lambda v ?', np.allclose(lhs, rhs))


lambda=2.0  A v == lambda v ? True
lambda=3.0  A v == lambda v ? True


In [39]:
C = np.array([[4., 1.],
              [2., 3.]])

# 1. eigenvalues and eigenvectors
# YOUR CODE HERE
print("eigenvalues and eigenvectors:")
vals, vecs = la.eig(C)
print('Eigenvalues  (lambda):', vals)
print('Eigenvectors (columns):\n', vecs)

# 2. print eigenvalues
# YOUR CODE HERE
print("eigenvalues:")
print('Eigenvalues  (lambda):', vals)

# 3. verify A v = lambda v for the first eigenvector
# YOUR CODE HER
print("verify A v = lambda v for the first eigenvector:")


eigenvalues and eigenvectors:
Eigenvalues  (lambda): [5. 2.]
Eigenvectors (columns):
 [[ 0.707 -0.447]
 [ 0.707  0.894]]
eigenvalues:
Eigenvalues  (lambda): [5. 2.]
verify A v = lambda v for the first eigenvector:


In [40]:
A = np.array([[ 2.,  1., -1.],
              [-3., -1.,  2.],
              [-2.,  1.,  2.]])
b = np.array([8., -11., -3.])

x = la.solve(A, b)
print('Solution x:', x)
print('Rank of A :', la.matrix_rank(A))
print('Full rank -> a unique solution exists')


Solution x: [ 2.  3. -1.]
Rank of A : 3
Full rank -> a unique solution exists


In [41]:
D = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [5., 7., 9.]])
print('Rank of D:', la.matrix_rank(D), '-> < 3, so rows are dependent')



Rank of D: 2 -> < 3, so rows are dependent


In [42]:
king  = np.array([0.8, 0.6, 0.1, 0.2])
queen = np.array([0.7, 0.7, 0.1, 0.3])
apple = np.array([0.1, 0.0, 0.9, 0.8])

print('cosine(king, queen):', round(cosine(king, queen), 3))
print('cosine(king, apple):', round(cosine(king, apple), 3))


cosine(king, queen): 0.986
cosine(king, apple): 0.267


In [45]:
A2 = np.array([[3., 2.],
               [1., 4.]])
b2 = np.array([7., 9.])

cat = np.array([0.9, 0.8, 0.1])
dog = np.array([0.85, 0.7, 0.2])
car = np.array([0.1, 0.2, 0.95])

# 1. Solve A2 x = b2
# YOUR CODE HERE
print("Solve A2 x = b2:")
x = la.solve(A2, b2)
print('Solution x:', x)
print('Rank of A2 :', la.matrix_rank(A2))
print('Full rank -> a unique solution exists')
# 2. Rank of A2
# YOUR CODE HERE
print("Rank of A2:")
print('Rank of A2 :', la.matrix_rank(A2))

# 3. cosine(cat, dog) and cosine(cat, car); which is more similar?
# YOUR CODE HER
print("cosine(cat, dog) and cosine(cat, car); which is more similar?")


Solve A2 x = b2:
Solution x: [1. 2.]
Rank of A2 : 2
Full rank -> a unique solution exists
Rank of A2:
Rank of A2 : 2
cosine(cat, dog) and cosine(cat, car); which is more similar?
